MSG_TYP_GOSSYP = 'https://didcomm.org/gossyp/1.0/message'
MSG_TYP_TRACE_REQ = 'https://didcomm.org/trace/1.0/request'
MSG_TYP_TRACE_RESP = 'https://didcomm.org/trace/1.0/response'
MSG_TYP_MRG_REQUEST = 'https://didcomm.org/mrg/1.0/request'
MSG_TYP_MRG_RESP = 'https://didcomm.org/mrg/1.0/response'
